* <2015-01-17 Sat>
Harry was sitting at the Ravenclaw table when black haired girl came up to him.  
* <2015-01-25 Sun>
Kyle jumped to the right, dodging the bite of a mutated rat.
His crowbar, covered in what was left of his previous enemies, was shaking in his hands.
Right behind him was a narrow river with ominously looking black water.
In front of him, as far as the eye could see, were the lifeless postapocaliptic wastelands.
Well, almost lifeless.
Between him and his home - only visible as a dim shape of several hills in the distance -
was a group of nuclear rats. Group or a pack? Or a pride?
Very soon they would be nothing. Because 3 rats were already lying on the ground lifeless,
and the remaining 4 were looking more and more hesitant to attack.

Rats were pretty useless, clever animals, but too aggressive.
Despite Kyle's attempts, the project of domesticating these creatures hasn't been a very successfull one.

* <2015-01-31 Sat>
** Singularity outline
Solving OM and singularity today!!
- Bottom-um procedural code-style singularity draft
+ Complete one of the drafts and turn it into a post.

Where do they gather.
Okay.
in this version they rent something like a co-working space from the dude.
Dude? Maybe inherited it from somebody, maybe made enough money to buy it, whatevre,
doesn't mater right now.

How does it look like?
Co-working office?
Or house?

Again - DON"T be shy to copy.
Go for what's more awesome.

House is more awesome.
Dude has it in New York.
Inherited or something.
And created an ad - come here, rent my space, blah blah blah.
Seth. Yes, name of the dude is seth right now.

Kyle, Scientist(name? Mike. Works. Don't linger, not important, biggest steps.) and Alice move in.

Kyle and Mike are friends from college.

Alice? Sister? Somebody they've hired? She knew about them and decided to join?
How did she knew? Maybe she's into Kyle or probably not.

Ok. Alice meeting Kyle and mike is a separate story, I'll figure it out.

So.
- Kyle and Mike meet in college.
- Alice joins them - separate story
- They all want to work in high-tech(robotics), which attracts them together (<<<< !!)
  but now just miserable webdev.
- They find a place, the house, which is in a perfect location and all. Seth rents it.

Got it. So they are living together, dreaming about high-tech, working on webdev temporarily.
Kyle is the leader.

Meanwhile, not far from them David(Amber works for him) are owning it at the kind of thing these guys dream of doing.

Computer vision for drones.
For now(procedurally), this is what his company does. Drones. Totally.

Now Max.
- Finds them how?
- Proposes what?
  
Okay, again, for now(need a word/symbol for that, procedural answer up to changing. #pin), he just finds them through the same ad/bulletin(how is it called?)

Assuming there's one more place in there. And also this house is really cool(for reasons, #pin).
It is so cool that Max maybe forces his place into it.

At the moment we begin, them working together is a back story.
Max joins them and that's where that begins.

So!!
Main questions:
- What could they need that would piss David off?
Max realizes that they need it, proposes it, they go, recruit Amber(David is possibly in love with her, she just isn't), she betrays him, he is pisssed, destroys them, and they are left struggling. And that's where they begin to hack.
Maybe Max even goes - hey guys, I got you into this, I can help you get out of it.

Kyle desperately wants to be in high tech, David is in the high tech. There's an answer there.
Kyle is sick of doing webdev.

Lets say he wanted to develop a product for drones.
YES!! He didn't want to steal the technology, he wanted to be the first on the market!!!!
David's company produces drones.
Their big product is coming up, like a google driverless car or something, big size.
Maybe freaking drone taxi or some such.
And Kyle is sick of webdev, and desperately wants the startup in this field!!
And he knows that if he can develop a product for that - he is in, he will dominate it!!
He does /not/ need to steal the technology, but he does need the source code and plans of drones, so he could start developing for them!!
THAT is what they discuss, and THAT is what Max proposes to do!!!!
YES.
Got it.

So!!
- Kyle and Mike meet in college.
- Alice joins them - separate story
- They all want to work in high-tech(robotics), which attracts them together (<<<< !!)
  but now just miserable webdev.
- They find a place, the house, which is in a perfect location and all. Seth rents it.

They all dream about high-tech, Kyle is sick of working for webdev, it's a temporary gig,
dead-end. They NEED to get into robotics. Plus that is the reason Alice/Kyle are with him.
They don't "expect" it from them, but he knows that it's the reason they're with him.

David's company coming up with a driverless-drone-taxi soon.
Fucking huge product, and in the field of their dreams - robotics, opencv, all that.
Their chance to break in(especially as webdev goes worse and worse, and they almost abandon it completely, betting everythign on this product, have been developing it for a while now, and now need to know some inside information).

Max is a self-taught hacker but NOT a superheroe. Which is why they fail, and which is why they all struggle with hacking even wth him on board. He is clever and knows a lot, but is still young and compared to true pros(who work for David) isn't that good. But arrogant optimistic and confident(which is why he tries. But not stupidly though).
He moves into New York, because that's the dream and everything.
By the way that might be a reason they are in NY and not in Silicon Valley. And David?
Whatever, he has a huge tech company in NY. If it's fine for Tony Stark to be in NY, it's fine for David too, he is not exactly a startup, it is a Massive Dynamics like R&D company.
So. Max moves into the NY, finds this house - for the same reason all these guys do, it is attractive to them for reasons.
//(are there such houses in NY?) Works for now.
He gets his way in.
//Max works as a consultant/hacker or some such, not important.

Kyle, Mike and Alice discuss how badly they need to know how these drones work for their product to work. Or maybe they were developing a general product, but now it's a huge enormous opportunity to them. It is also clear that Kyle is fucking sick of the dumbass webdev, he is young and ambitious and dreams about high-tech and everything.
(by the way, this is why it can be so funny, when I come up with legit projects for them - make clients retarded and projects ridiculous. Like a cookie recepie website. And Kyle, this hardcore badass talking to that half-crazy old lady. Just grim look on his face. Cookies? REALLY?! Goddamit motherfucker!! Maybe dude is the only one who helps them to get through this).
Yes. So there's this cookie-client. I'm done with this, not tolerable anymore, we NEED to break in on this opportunity.
And Max overhears that(maybe they're not too friendly att this point, probably he has forced his way in or such) goes like - Here's an idea. I know a way of getting into the David's company.

Does he know amber or recruit her?
Amber is definitely not the dumb blonde to be seduced, but let's put a pin on that too, there definitely is a way.
So. Max recruits Amber.
They all begin an operation to get the drones source-code(#wv - working procedural version?).
Amber helps them.
It would be not even be such a big deal(illegal, but nothing too horrible, especially considering the intentions), but(?) on top of all that David is in love with Amber, and they get her to betray him(maybe more serious than that, maybe it /is/ very illegal).
So they get caught, and David knows what they were trying to do, what they really want, and knows that Amber betrayed him.

So David:
- Fires Amber - fuck you.
- Says to Kyle that he will destory his dream, he will NEVER work in high-tech/drones,
  he will make it his personal mission to crush every attempt Kyle has, David has resources to make superior version of his products and dominate it, etc, there are many ways.
- Says to Max that he is also screwed somehow. 
  Maybe Max is also hacker on the side. Maybe he even wanted to work for a company like David's!
  Maybe it was his way to show off his skill anyway!(#pin), but he did that through Amber.
  And David says - you are done in this counry, no company will ever hire you.
  
YEAH. Pin on all that, but makes sense now.

So!!
Kyle/Alice/Mike are screwed because their company and dream is fucked.
Max is screwed because his ~dream to work as a hacker for a huge high-tech company is fucked.
Amber is screwed because she is out of the job and carreer.

And the only thing that is left for them is to make it together on their own.

Is it from POV of all of them or mostly Max?
For now(#pin) - make it like HPMOR, like mostly Max, but sometimes can be others too.


SO!!!!
The next day/week.
Dumbass cookie project comes to an end, they're out of money, out of work, and out of the dream.
Dude won't throw away them from his house, probably, because he's a dude, but he's also out of money as well. For the same reason =)

So. They are screwed.
And this is where we begin. I'm happy to have the outline of how they met, but now what I'm interested in is the regular monster-of-the-week episode.

//also they can TOTALLY have collegehumor-like office scenes!! They do have dumb clients to work for, and their own stuff to do. Each of them is probably freelancing on their own as well.
Besides they totally hang out and everything.

So yeah. This has EVERYTHING.

Now. How do they get into hacking?
Well, they are screwed at everything, they have already done their first hack and it is clearly something they are at least sort of good at, and definitely capable of doing, and if not that dumb mistake they would win, and this time they will be careful, and also they don't have much to lose anyway!!

And.... where do they find their first job? Who proposes it? Max again?
He has that buddy who needs x, or knows a guy who needs y.

General computer crime....
Probably from a smaller company.
It is also more like a cartoonish/simplified world of incredibles/futurama.!!

BOOM. Excellent.
The question is only what do they steal and how.
And THAT I can totally take from HPMOR/Futurama/Firefly/etc/etc.
Or come up with.
Cmon!!

And another fun thing is that they are total newbies at hacking, worse than WW at the beginning.
These criminal guys pay very well. Sorta.

Does Max have contacts? Does he have friends who have contacts?

So! Alright.
Max has a friend, put a pin on that too. It works.

He hangs, contacts him, and that guy mentions that there's that job.

- Abandoned spaceship? > Abandoned company with loot.
- Train job? > Steal something physical in transit.
- Laser? > Pure break, enter, download data job.
- Niska? > get in trouble with criminals.
- Ariel? > 2 of them are downloading data as alarm goes off(no betrayal).
- Whorehouse? > protect a website from ddos or someting? Fight off another group of hackers.
- HPMOR battles? > Wining Defcon hacking competition!! (to get in the door somewhere, or fun)
- Wizengamot? > Defending net neutrality, making sure a bullshit law doesn't get approved.
- Saving Hermiony? > They freak out that Alice could be in danger, when they come to save her turns out that she kicked all the butts there were to be to kick.
- Inception? > Convince a guy to not sell his company or something, by helping/protecting/manipulating him. Maybe all 3.
- Prison Break? > Government agents are onto them.
- Pranks competition? > Competition between Max and Kyle, bet, who beats whom and such. Maybe breaking into 2 teams, 3 vs 3. on sometihng.
- Harry vs Tracey? > They all have decided to try LSD, when something comes up they need full alertness with.
- Harry vs peeves? > trolls come together on reddit to ddoss/attack them/their friends company or some website that they like? And they destroy trolls from the inside or some such.
- Agents? > They decide to infiltrate some company to find out the secrets, something super secret and exciting. Not as a job but because they need to know.
- Criminals take someone hostage?
- Woman, husband, the bank where he holds his money?
  
FUCK. YEAH.
Fuck yeah indeed =)


----


Okay. Important thing - not getting stuck.
Max has a friend with a job? Works. Put a pin on that, pivot later, now just move forward.

So. They are screwed, Max says I have an acquaitance.(friend? No, not friend, acquaitance. Something like that low-life criminal from firefly). He pays money... sort of...
On the upside - it shouldn't be too hard.

Great. It works. What needs to be done?
Steeling data.
What data could a criminal need to steal?
Well, maybe not low-life, maybe mafia or something.
Or even funnier - maybe Max thought these are just like some guys, and turns out it is some sort of terrifying organized crime-boss.
Which are probably also not what it seems.
Yeah, there may be something interesting there.
they first thought it's just some little guy needing to steal some competitors passwords and such.
Then they find out it's mafia - like what the hell would mafia need some little guy's passwords for?
And then as they retreive passwords(list of employees or such) they find something super weird, and turns out that little guys are not little guys at all, but instead a cover for something big and top-secret. And now there's no turning back.

Would be great to know what that is exactly.
- What do they need to steal?
- How do they get in contact?
- What it turns out to be?

What kind of innocuous thing could that be?
Like list of passwords? Employees?
Pretext-reality.
Like list of employees, which turns out to be a list of government agents?
(remember, cartoonish inception/futurama, can be very far and hilarious.)

What could mafia use for something evil, but not too horrible? But rather funny.
Like they thoiught these guys will maybe outcompete some small teacup comany, and they anded up doing something huge.

So.
- Max's friend. I have that guy who knows that guy, who has a hacking gig.
  Don't worry, it's nothing too big, and this time it won't be dangerous, we will be careful too.
- They have a meeting, turns out it's mafia. Uncertain but maybe pressured to take the gig, or convinced after doubts that it's not such a big deal.
- They work on it and get in, and see something strange/weird.
- They retreive and return the info.
  //mafia tries to kill them/get one over them? maybe they just have a video/proof for blackmail, not necessarily shooting and stuff. And they gets it back. Maybe in another episode.
- The next day they read in the news that they've unintentionally participated in something friggin huge. Turns out some crucial information from a giant com[any got leaked. And it is hilarious.
  
BOOM.
//And WHOAh. Wait, wha-at?? Was that above maybe an outlining process?? Or some glimpse of it at least.

Anyhow.

Great!!
- So what is it specifically that they are trying to retraive?
- And what does it turn out to be?
  
What can you possibly steal?
Passwords? Employee data? Some invention stuff?
> or you could put a virus INTO the network!!
That is by the way also very interesting, and seems easier too!! You just need to get in and make somebody to open a document/insert a memory card!! That seems even smaller/easier!!
And it is totally pure SE gig!!

And mafia could say thaat it is a little backdoor into their system.
But turns out it is....

well, the interesting thign is that it depends on what company that is!!
For example if it's a facebook that can be a personal data,
if google - that could be some secret algorithms,
 if dropbox - some corporate secrets. Of the whole friggin world.
if paypal - money.
if amazon - maybe like control of the drones or some such.
if android - well, tracking people and personal info and maybe viruses and such!!
if comcast - maybe destroy the internet in some particular area/building....
or, of course, bug some particular person.(like ghost in the wires. By the way, his books have infinity of ideas for me!! Cheating the casino and such!!).
>>>> a-a-a-and here comes my excuse to learn hacking =) By the way yeah, not now, but over time there could be more and more details about how exactly they are doing it. realistic details.
From Mitnick.

Besides, just like HPMOR, induces the desire to google. Good thing.

So.
//maybe some of them are in college too? Kyle, Amber, Alice, 

Why are gangsters chasing them?
Maybe after realizing what they had done they've decided not to give the info to them.
Where do they get money then? Did they have any avance? Will they have to return it?
What do they have on the gangsters?

** Bottom-up procedural code style
<!--
Amber(22 years old, bulky but comfortable cloth, shuffled red hair) was sitting on the floor tinkering with wires on the raspberry pi project that she was making.
Mike(21 years old, buttoned-up t-shirt with a pocket protector. Seriously.) was sitting on the couch and reading Feynman's lectures on physics(Volume 1) for a 4th time.
Alice(16 years old, long black hair, very lean) was sitting on the opposite end of the couch, abscentmindedly doodling something in her tablet.
Usually relaxed and careless Seth(28 years old, slightly overweight, very hairy and beardy) was playing xbox, but he kept losing the same simple level, his heart wasn't in it.
Kyle(24, shaved head, goatee, long coat, piercing sight from behind his augmented reality glases) was standing in the center of the room, staring intently at Max(22, black shuffled hair and short beard, black jeans and shirt with an orange tie, also in glasses - narrow rectangles. Bright and intent brown eyes, with strikingly sharb and saturated, almost orange retinas), who looked back at him from behind his thinkpad x4.
-->

*[2031-03-20. 03:16AM]*

Sounds of several gunshots echoed in the abandoned metro station.

A few bullets blasted the column right above the Max's shoulder as he dived into the space between trash containers to get away from the line of fire.

He estimated that they had about half a minute, so he got back to vigorously typing in his laptop. "Hey, that's what I call 'agile programming'!"

Kyle didn't appreciate the joke. He was hiding behind another column, watching 4 people in expensive suits and with guns in their hands running in their direction. "You've said it will be safe! You've sayed it will be just a simple job!"

"Well, the next time we will be more careful"

"The *next* time?! You gotta be high to think that I will agree to something like that again!"

Max just smiled. Typing has slowed down and then stopped with the victorious hit on enter key.

"Now we just give it a minute for it to work. Do you have any idea how do we last a minute without getting shot?"

<!-- PELICAN_END_SUMMARY -->

----

*[2031-03-11 12:36]*

Tiny old house, one of the very few that still left in the center of a big city.
Group of 6 people gathered in the biggest room on the first floor.
All of them looked thoughtful and grim.

"So I take it we're completely screwed, huh?" abscentmindedly mumbled Alice(16 years old, long black hair, very lean) from the couch, without taking eyes off her tablet that was propped against her legs, where she was carefully drawing something. 

"Uh-huh" responded Mike(21 years old, buttoned-up t-shirt with a pocket protector. Seriously.) . He was sitting on the opposite end of the couch, and reading Feynman's lectures on physics(Volume 1) for a 4th time. He was always reading when he was fighting stress. Or not. He was always reading, really.

"How did we manage not to get this one? It was a website for a baking company for ktulhu's-sake!!" asked Amber(22 years old, bulky but comfortable cloth, shuffled red hair), although they all knew perfectly well how "I do not blame Kyle for not pushing on that one, of course" she was sitting on the floor tinkering with wires on the raspberry pi project that she was making. Very, very rarely there was a moment where you could see Amber without a cheerful simle on her face. That was one of thouse moments.

"I'm telling you, guys, I should've negotiated this project. You all are bored to death with this kind of work, and it shows, I don't really care, so I could've talked them into letting you do the job" Usually relaxed and careless Seth(28 years old, slightly overweight, very hairy and beardy) was playing xbox, but he kept losing the same simple level, his heart wasn't in it. The last part of the sentence rose to the intense scream, as a figure on the screen was firing hell on crowds of aliens.

"Yiii-ha!!" Max(22, black shuffled hair and short beard, black jeans and shirt with an orange tie, also in glasses - but regular ones, simple black narrow rectangles. Bright and intent brown eyes, with strikingly sharp and saturated, almost orange retinas) looked up from behind his thinkpad x4, happy smile dawning on his face.

"What?" Kyle(24, shaved head, goatee, long coat, piercing, intent, intelligent sight from behind his augmented reality glases) was standing in the center of the room, staring intently at Max.

"I've got an idea! I've got this friend who..."

"Uu-ugh..." - from every person in the room. Not again.

"No, hear me out!! This time it's legit... Almost. Well, at least less illegal. And *definitely* much less dangerous!" they've had this conversation before, but Max was certain that this time he will convince them. They didn't have much of a choice really. He was the only one really excited about a prospect of doing some hacking - he always found it invigorating - but he was pretty sure that all of them will really enjoy that too, eventually. Even though it really didn't seem possible right now.

"Alright, what do you have?" said Kyle, as everybody were staring at him.

Max's simle grew even wider. I knew this time it will work!! As cautious Kyle was, he was clealry more sick of the boring projects than any of them, and he may not like admitting it, but Max remembered very clearly how excited Kyle was on their last and only hack. Despite how that all turned out... Kyle may not think that hacking is very prudent, but this time he will take the interesting and challenging project he was craving for for so long.

"I have this... acquitance... who says he has a job for us. It won't be like the last time, I promise. It is a small company that doesn't take their security very seriously, and he says that all we need to do is steal some data from them for their competitors. Cmon, let's at least hear what do they have to offer!"

"Fine. Setup a meeting." Kyle's voice was still stern, but his face got noticeably less grim.


----

*[2031-03-14. 02:36AM]*

Man in the expensive black suit was standing in the middle of the old metro station, looking bemused. Two serious-looking guys in sunglasses(In the metro. At night.) were standing by his sides. "What did you choose this place for?" said the man, a little concerned. "Couldn't we met in starbucks or something?"

Kyle and Max looked at each other. From what Max knew about that kind of meetings from movies, he assumed that the old abandoned metro station was the way to go, besides he thought that this could impress 'an owner of a small company, a regular guy' his acquitance said they were supposed to meet. Now he himself was a little nervous, the guys that were standing in front of them were looking more like some low-level thugs. Thakfully, they were looking confused and unthreatening.

"This is more private" said Kyle, assuming the authoritative tone, Max firmly nodded.

"So" said Max, "what job do you have for us?"

"Recently we learned that our, uhm, competitors, got some data about out company. Private data abot our employees mostly, and also some financial and buisiness information that we would like to keep secret. What you will need to do is to find and destroy all the information they have on their servers about our company"


*[to be continued....]*

<!--
----

This moment a train
-->

** .
- Scene of Max proposing the hack
- Scene where Dean asks them to enter the competition
//Scene where they prepare for break in(to have a new scene to write)?
  
Six people gathered in a small studio aparment.

Beats:
we're screwed (-) > I have a solution + > I dislike the solution (-) > convinced +.
- Small apartment, 6 people in it.
- We're screwed. last project was horrible and even that failed.
- Kyle hates boring projects.
- Max - almost legal solution.
- Was sure Kyle will agree. Kyle agrees.
  
Tiny old house, one of the very few that still left in the center of a big city.
Or maybe it just appeared that way, compared to the giant, new, and shiny city.

Group of 6 people gathered in the biggest room on the first floor.
All of them looked thoughtful and grim.

"So I take it we're completely screwed, huh?" abscentmindedly mumbled Alice(16 years old, long black hair, very lean) from the couch, without taking eyes off her tablet that was propped against her legs, where she was carefully drawing something(the something depicted the previous clients, being screwed instead of them).

----

The study group gathered around the table.
Before anybody had time to say anything, the Dean suddenly appeared in the doorway.

"Oh, crap, I have just started hoping for a nice, normal day. I guess that doesn't happen in Greendale, does it?" thought Jeff out loud.

The Dean was wearing a fabulous light-blue dress, a wig of long light hair, and carrying 3 small stuffed dragons on his shoulders.
"Hello everyone!! I am the Deanarys Targaryen, the mother of dragons, and I am here to tell you that our school needs your help. Greendale is not the best school, but for generations we have been proud to hold the award for the best pacman score in the area, until City College took it from us 5 years ago. And now I am proud to say that we have an opportunity to get this honor back, return Greendale it's throne, so to speak." said he in a loud and cheerful voice while pointing at his dress.

* <2015-02-01 Sun>

Short, 5-minute , visual, present tense, diverse fiction stories. Screenplay-way.

Characters in a situation.
I've got settings, and I've got characters!!
Need only 2, cmon, it can't be hard!!
Cmon!! Pick 1 setting and 2 characters.

Ideas:
- Agents vs aliens. Michael Cera and Theodore Bagwell fights aliens.
- Grandma Tyrell vs Saul Goodman
- Airbender, element magic.(worst person to have it?)
  Displeasing guy(gets superpowers. And Kaylee, his assistant.
- Harvey/Jessica vs zombies.

- Benjamin Linus and Turtle fight robot rebellion.
- House vs Jessie Pinkman fighting Dinosurs 
- Frank Underwood + HIMYM(haha, nice one. He's telling his children)  
- Dexter pony.(okay, that's funny))

//Hermiony and Juno
//Nuclear postapoc.
//Vikings vs dragons. 
//Avengers. Gollum is a superhero.


-
Mike looked at the giant antient starship hanging above the canyon.
It was hanging there for generations, as long as anyone could remember.
Nobody have ever understood how did it work, nobody was even able to enter that thing.
Because they were living in the cavemen times.
And cavemen could never get into the spaceship.

-
It was a regular day for a Saul Goodman.
He helped one guy to get out of jail for dealing weed, and helped that creepy lady to get every penny her husband has ever owned or will ever own.

-
Meanwhile, Jane was sitting outside of the office, tweaking the latest security software that run their corporation, when she learned that her boss developed magical powers.
One of her laptops keeped the skype session with her boss opened, since she was trying to convince him not to open that kitten picture link in his email.
Apparently he forgot about that in the last 15 minutes, and now was abscentmidedly picking his nose while reading something on his computer.
She didn't tell him that she could see him immediately, and after awhilie it was just awkward,
 2Suddnly that picture grabbed her attention, as she saw something like a purple explosion from behind her bosses head. Boss clearly didn't notice any of that, as he was paying all his  attention to the computer screen. Jane just wanted to tell him something, as she noticed that a pen he held in his hand, again, unbeknown to him, disappeared in the burst of flames.
Boss kept reading something on his screen, laughin from time to time.

//some dummie gets magical powers, and a cool clever guy has to manipulate this idiot into doing what he wants. Cool. But dummie needs to also be cool and likeable. Maybe not stupid but just not the kind of character to use magical powers very well.

-
Harvey was sitting in his office when he didn't notice that something strange was happening in the city. He didn't notice because his office was on the 60th floor of a huge scyscraper.
This was a regular morning,

-
Ben and Sal stood back to back, shooting lasers at crowrs of robots that were trying to get through the doors of their building. Robots were humanoids, and looked a lot like scary sceletons. Sal wondered - why would you make a robot looking that weird? Granted, friendly-looking robots were looking even creepier, but then again - what is the point of designing a thing to look outright malicious? Almost like designers hoped that these robots will rebel. You could hardly see these things assembling cars or cleaning the streets or babysitting.

-
Loudest roar echoed through the entire forest, as a humongous foot landed in 2 meters from the Jessie. After a second of stunned silence, Greg grabbed him by hist shirt and started running in the opposite from the foot direction. They will take time to explain what is going on later, now it was clearly the time to run. They had no reasons to suspect that T-Rex would have any interest in them - after all, he would hopefully perfer a much bigger prey, but this pack of raptors on the other hand....

-
Frank was having his first date in a long long time. After 20 years of ruthlessly climbing the corporate ladder in the biggest and meanest software corporation of all time he almost forgot what's it like to talk to a person without a clear agenda or buttons to push.


* <2015-02-03 Tue>
Vikings,
Superheroes
Aliens,
Postapoc,
Pirates,
robots,
dinosaurs,
magic.

Universal core chars:
> Main
Hermiony //Kaylee?
Juno     //Robin/Lindsay,
Harry,   //Frank/House/WW/etc
Twins    //Barney
Draco.   //

> Secondary
Jeff
Marshal/Seth/Turtle,
Abed,
Captain,

> Other
Louie Ck
Michael Cera
Shirley
Pierce/Chang/Dean
Troy
Luna
Grandma Tyrell


Alright, got my core chars.
Look it doesn't matter just shut up and write.
Pick any 2 of them, don't need more.

Hey!! Here's one thing I haven't concidered: the real world!!
It may actually be pretty awesome.
It is already developed. It has most of the stuff that inspires scifi....
I totally need to list the cool real world settings!!!!
Of course, makes A LOT of sense!!
OF COURSE!! Great idea dude!!
Professions too


- Pyramides
- Stanford/MIT
- Hot startup
- Boston Dynamics/google R&D
- Canada
- Australia
- Small town
- New York
- Law firm
- Collegehumor workplace
- Mancave, xbox, couch
- Hollywood
- Small african village
- Detroit
- Metro
- Submarine
- Jet
- Abandoned hydron collider or such
- Small tropical island
- 
//Check all of them in the past/present/future

Professions:
- Scientist/Mathematitian/Engineer/Programmre
- PUA
- Detective
- CEO
- Writer/Artist
- Drug dealer
- Douchebag Lawyer
- Evil Machiavellian polititian(not only in politics, in any field)
- 


Okay, probably what's more important is to actually be coming up with IInc's!!
- Somebody attacks you on the street
- Aliens/other dimension creatures are coming
- Dark overlord rises
- Competition/sport
- You got setup for a crime
- Stray in a dangerous place
- Priceless artifact has been stolen
- Your friend is in danger, have to resque
- Crime appened and needs to be solved
- Somebody hurt you
- Enemies attack your castle
- You've met a girl who is ignoring you
- Once in a lifetime opportunity that you need to win whatever it takes
- Somebody is chacing you
- You're out of money and out of stuff
- Your best friends had a huge fight and now hate each other
- Somebody gave you something very dangerous to take care of(like a pet)
- 
More specific:  


Also I might probably need an antagonist.


#prj I could totally make prompts =)
- 2 protagonist characters.
- One antagonist.
- Setting(scifi/place)
- Goal/IInc
Optional:  
- Genre
- Controlling idea(essay/lesson to learn)
- Secondary
//something to munchkin? what do these rationalist guys do again? Solve a thing?
//additional challenge - x number of words, start with a letter, make it rhyme, make it start with "banana" and end with "ostritch"
//Image!!
//Submit yours. Basically just shoot me a message with ideas on how to improve.
//de-bono jumps!! reverse, exaggerate, random word. Breakdown.
////story structure? cards and blahblahblah. probably not.
interface?
random prompt
(update all, update this one),
list of all the options(I'm making a thing for myself, not for dummies)
tools.om.io
- writing prompts
- creative thinking tools
- story structure and stuff. Questions you need to ask. 
  //Textbook improving a thing.
////planning organizing and visionary and shit. nah. just use emacs =)


Alright, interesting!! IInc actually seems to be the most helpful.


So.

* <2015-02-04 Wed>
>>>> Perfect format: 5-min shorts, visual, present tense. Screenplay-way. (= Setup given)
>>>> 2 characters + Settings + IInc is where I start.
- Character(s)/Setting/IInc
- Bottom-up explore. Have a draft of something. Scene, chars in a situation doing stuff.
- Use it as a setup for comedy.
  
