* My Perfect Worlds
** Commpunity 
** Incredibles
 - my HPMOR // Worm,
** Singularity
   = RaM meets Futurama //Firefly
** Mirage
   = Deep meets Inception //permutation

* Ideas
Incredibles:  
- battle
- getting into the school
- social engineering lecture
- 
 
 
Community:  
- Competition with city college. Get back the throne.
- Somebody blew up the studyroom and they all have lost their memories
- Abed (/de)inception in dreamatorium
- cloverfield? 
- paintball sequel?
- computer game sequel?  
  
  
HPMOR:  
- Ron is in love with Hermiony. He knows harry is superior, gives his best to come up with a plan to defeat his evil.
- Harry vs Twins - pranks comppetition
- Harry vs Tracey - rationalist on a love potion
- Harry wants to do experiments on ghosts, they are too proud
- Belka strikes back. Takes Nevill hostage?
- Harry vs Dumbledor, over taking control of his money!
- Retreive books from the restricted section
- Harry vs peevez.
- Broomstick battle and battle where all three generals get assasinated at the beginning
	I want to hear about Draco thinking that between Goyle and himself, it's an easy win for Dragon Army. And then he decides to have Goyle attack Sunshine single-wandedly. I want to hear about how Hermione can barely get off the ground and after 30 seconds of Goyle, Sunshine's chances are all up to Ron Weasley and Susan Bones. Who then decide their only hope is to run toward the Chaos Legion and hope the Chaotics and Dragons will focus on each other until the numbers are more even.

	I want to hear Harry's aerial battle tactics, how Tracy Davis and Theodore Nott gang up on Draco, and how well Finnigan and Thomas fare against the other Dragons. And ultimately, I want it to come down to Harry vs. Goyle pitting training and experience vs. talent, creativity, and intelligence. All while Harry is too distracted to notice that his broom always flies in the direction it's pointed.
- Battle where everyone is for themselves.
- More of the cans of comed-tea

Diverse short stories(/premises):
- Fallout meets How to Train your Dragon
   Befriend a monster in a nuclear wasteland
- Nerdy Magician + Pirates
   Nerdy magician kidnapped by pirares, escape-befriend them
   //silicon valley+pirates+prison break
- Character realizes he is in a story
   Writer, extremely genre aware, recognizes he got into a story.  
   Uses it as a power, predicts stuff, argues with a narrator.
   //californication(cocky dickhead writer)+LOTR

   Like "wait, that can't happen! Even if magic is real, this part is
   just a cliche, it dkesnt make sense! I'm in a story!!"
   "narrator: and trolls blasted into the building
   - hey, why'd you do that to me, dickhead? x and y is why you
   never do that in a story.
   narrator: oh, nevermind then, okay, trolls don't blast into the 
   building.
   haha, maybe narrator gets even angry and dumps bucket onto 
   a character's head or something"
- MIB for paranormal.
   MIB+ fringe(paranormal scientists) Comedy. World where werewolves/magic/
   etc are real, and agents have to deal with it.
   Yeah, like a newbie agent is assigned a mission to deal with a 
   stray werewolves!! Not HP world, or maybe heck, maybe HP!!    
   Imagine US agents who are aware of magic.

- Space pirates crew stray on a mysterious planet, try to escape.
   //lost(plane crash/mysterious island)+Firefly

- Supervillain apprentice  
   //Suits + megamind/dispeakable me

- Inception into mind of a suspect to solve a crime
   Sherlock

- Max, steal data, villains. in Futurama this time.
 
- breaking bad - scientist turns bad

- portal - experiment subject

* Settings
- Vikings vs dragons. //How to train your dragon
- Agents vs Aliens //MIB
- Nuclear Postapoc //fallout
- Laboratory, mice //pinky and brain/ratotuille
- Pirates plus Magic //Pirates of the Carribean
- Robot world //Terminator/WALL-E
- Alien planet //Alien
- Dinosaurs //Jurrasic Parck, land before time
- Zombies //Resident Evil/Walking Dead
- Illegal underground Science research lab. //fringe
- Element magic + knights/fantasy //Airbender + GOT


* Characters
Tyler Durden, Cannibal Lecter,  Joker, Gollum, Abagnale, Jack Sparrow, terminator, Michael Cera, Petyr Baelish, Arya Stark, Socyopath Tyrell, Tywin Lannister, Grandma Tyrell, Khal, Frank Underwood, Lex Luther/Tony Stark, Jessie Pinkman, Hermiony, Juno, Barney, Saul Goodman, Kaylee, River, Shepherd, Inara, Jayne Cobb, Zoe, Mycroft, Mrs. Hudson, Claire Underwood, James Sawyer, Kate Austen, Hurley, Benjamin Linus!!, Lost Physicist, Debra Morgan, James Doakes, Trinity killer, Angel Batista, Creepy Chinese guy(Dexter), James Willson, 
Harvey, Rachel, Donna, Louis, Jessica, Howard,
Linsday, Bad girl from(FaG), Cool Nerd(FaG), Marshal, Theodore Bagwell, Alexander Mahone, Gretchen, Agent Kellerman, 
Grandpa(Up), Louie CK, 
Abed, Britta, Annie, Shirley, Troy, Pierce,
Satanist(Silicon Valley), Displeasing,


* Plots
- Fight a villain/opponent
- Get out of trouble
    Escape plan that went wrong
    Get setup for a crime
    Stray on a dangeroud planet
- Retrieve an artifact. Find/Steal a thing //inception
- Resque someone
- Break into/out of something
- Solve a crime
- Exact revenge
- Fix what is wrong with the world
- Protect a place from an army //whorehouse, alien invasion
- Get/impress a girl/person
- Win/close a deal
- Escape from agents/creatures
- Take over something //villain, world
- Any other goal of value
    Make money. 
    Make a Discovery.
    Unite the worlds.
    Take home to the adventure place(Up)
    Return a girl home(Monsters Inc)
    Restore a family(back to the future) //get out of trouble
    Bring humans back to earh(WALL-E)
    Retain a memory of a girl(Eternal sunshine)
    Win at political stuff


* Source stories
HPMOR; RaM; futurama; Inception; matrix; Firefly; incredibles; avengers; x-men; train your dragon;star wars;MIB;fallout
pinky and brain; airbender; got; lost; pirates of the carribean;batman;LOTR; fight club; terminator; alien;liar liar; mask; jurrasic parck; resident evil;
silicon valley; californication; fringe; lost; community; HIMYM; walking dead; futurama; sherlock; Dexter; house of cards; house; dr who; suits; prison break; breaking bad; d&d; halflife; portal; megamind; dispeakable me; lion king; walle; ice age; shrek;  emperors new groove; inspector gadget; 

* Genres
- Complex plots //house of cards - one politics plot
- Supervillain story //megamind/dispeakable me
- HIMYM - lovestory/romcom. 
  Yes, that too. Be creative.
- Mystery/Whodunit //sherlock. Remember yam killing.

  
* Essays
*** Creativity
***** DeBono Creativity Inventions
****** Creative pause.
****** Jump
****** Move
****** Breakdown
****** Penetrate(MVP, EP) + CI > Pivot-Steer
****** Drop expectations, list of 5.
****** Strip away everything unnecessary. Get to the core. Minimal thing.
****** Paradox of choice, good enough principle.
****** Reverse enineering.
****** No rules just tools.
****** Comedy
       Joke structure.
       AIMA epiphany dean's book. Defeat expectations.
****** Imagination.
****** Jump-unfold.
       Get into the world and explore.
****** Get most of the ideas in the process of writing.      
****** Niching down to make ideas
****** Curiosity. How it works.
****** Ideas of value. Not about typing/expression.
       Substance, story. Fuck grammar. 

****** How I want to write - concise, simple, etc.

****** Reasons we enjoy movies. Comedy. Mastery. Etc.
       Avatar. Association.
       Value. Closer/farther from goal.
       Conflict. That makes sense.
       Event - moving closer to or away from the goal.  

* 2015-01-16
So!
Setting.
Character(s).
Plot.
Premise.

Befriend a monster in a nuclear wasteland....
 



