* My Perfect Worlds
** Commpunity 
** Incredibles
 - my HPMOR // Worm,
** Singularity
   = RaM meets Futurama //Firefly
** Mirage
   = Deep meets Inception //permutation

* Ideas
8 posts:
- Nerdy magician
- Incredibles - first day
- Pacman competition
- Singularity bottom-up  
- Essay(comes last)
//
- ?Singularity - max and criminals
- //Xkcd collegehumor ~ singularity?
- ?Mirage -?
- HPMOR 
  
Incredibles:  
- battle
- getting into the school
- social engineering lecture
- 
 
 
Community:  
- Competition with city college. Get back the throne.
- Abed (/de)inception in dreamatorium

- Somebody blew up the studyroom and they all have lost their memories
- cloverfield? 
- paintball sequel?
- computer game sequel?  
  
  
HPMOR:
- Harry vs Twins - pranks comppetition //+More of the cans of comed-tea  
- Harry vs Tracey - rationalist on a love potion
- Harry vs peevez.
- Agents  
  
- Harry vs Dumbledor, over taking control of his money!
- Ron is in love with Hermiony. He knows harry is superior, gives his best to come up with a plan to defeat his evil.
- Harry wants to do experiments on ghosts, they are too proud
- Belka strikes back. Takes Nevill hostage?
- Retreive books from the restricted section
- Broomstick battle and battle where all three generals get assasinated at the beginning
	I want to hear about Draco thinking that between Goyle and himself, it's an easy win for Dragon Army. And then he decides to have Goyle attack Sunshine single-wandedly. I want to hear about how Hermione can barely get off the ground and after 30 seconds of Goyle, Sunshine's chances are all up to Ron Weasley and Susan Bones. Who then decide their only hope is to run toward the Chaos Legion and hope the Chaotics and Dragons will focus on each other until the numbers are more even.

	I want to hear Harry's aerial battle tactics, how Tracy Davis and Theodore Nott gang up on Draco, and how well Finnigan and Thomas fare against the other Dragons. And ultimately, I want it to come down to Harry vs. Goyle pitting training and experience vs. talent, creativity, and intelligence. All while Harry is too distracted to notice that his broom always flies in the direction it's pointed.
- Battle where everyone is for themselves.
- More of the cans of comed-tea  


Diverse short stories(/premises):
- Fallout meets How to Train your Dragon
   Befriend a monster in a nuclear wasteland
- Nerdy Magician + Pirates
   Nerdy magician kidnapped by pirares, escape-befriend them
   //silicon valley+pirates+prison break
- Character realizes he is in a story
   Writer, extremely genre aware, recognizes he got into a story.  
   Uses it as a power, predicts stuff, argues with a narrator.
   //californication(cocky dickhead writer)+LOTR

   Like "wait, that can't happen! Even if magic is real, this part is
   just a cliche, it dkesnt make sense! I'm in a story!!"
   "narrator: and trolls blasted into the building
   - hey, why'd you do that to me, dickhead? x and y is why you
   never do that in a story.
   narrator: oh, nevermind then, okay, trolls don't blast into the 
   building.
   haha, maybe narrator gets even angry and dumps bucket onto 
   a character's head or something"
- MIB for paranormal.
   MIB+ fringe(paranormal scientists) Comedy. World where werewolves/magic/
   etc are real, and agents have to deal with it.
   Yeah, like a newbie agent is assigned a mission to deal with a 
   stray werewolves!! Not HP world, or maybe heck, maybe HP!!    
   Imagine US agents who are aware of magic.

- Space pirates crew stray on a mysterious planet, try to escape.
   //lost(plane crash/mysterious island)+Firefly

- Supervillain apprentice  
   //Suits + megamind/dispeakable me

- Inception into mind of a suspect to solve a crime
   Sherlock

- Max, steal data, villains. in Futurama this time.
 
- breaking bad - scientist turns bad

- portal - experiment subject

* Settings
- Vikings vs dragons. //How to train your dragon
- Agents vs Aliens //MIB
- Nuclear Postapoc //fallout
- Laboratory, mice //pinky and brain/ratotuille
- Pirates plus Magic //Pirates of the Carribean
- Robot world //Terminator/WALL-E
- Alien planet //Alien
- Dinosaurs //Jurrasic Parck, land before time
- Zombies //Resident Evil/Walking Dead
- Illegal underground Science research lab. //fringe
- Element magic + knights/fantasy //Airbender + GOT

- Pyramides
- Stanford/MIT
- Hot startup
- Boston Dynamics/google R&D
- Canada
- Australia
- Small town
- New York
- Law firm
- Collegehumor workplace
- Mancave, xbox, couch
- Hollywood
- Small african village
- Detroit
- Metro
- Submarine
- Jet
- Abandoned hydron collider or such
- Small tropical island
- 


Professions:
- Scientist/Mathematitian/Engineer/Programmre
- PUA
- Detective
- CEO
- Writer/Artist
- Drug dealer
- Douchebag Lawyer
- Evil Machiavellian polititian(not only in politics, in any field)
- 
  
//Check all of them in the past/present/future

* Characters
Universal core chars:
> Main
Hermiony //Kaylee?
Juno     //Robin/Lindsay,
Harry,   //Frank/House/WW/etc
Twins    //Barney
Draco.   //

> Secondary
Jeff
Marshal/Seth/Turtle,
Abed,
Captain,

> Other
Louie Ck
Michael Cera
Shirley
Pierce/Chang/Dean
Troy
Luna
Grandma Tyrell


- Violet(Juno)
- Dash(Twins)
- Kyle(Harry)
- Pyro(Kylee)
- Magneto(Troy?)
- Seer(Luna+bright/positive/cheerful)

- Max - hacker. satanist/house/harry /security
- Amber - engineer. kaylee. / hardware
- Alice - SE. lindsay/violet/.. /designer
- Kyle - leader, captain /programmer
- Seth - dude hairy guy from silicon valley, seth, dude from big hero /rent, can talk anybody
- Mike? Alex? - Scientist. ML. Cool nerd from freaks and geeks, Abed /backend, systems, ml  
  
** Examples  
Tyler Durden, Cannibal Lecter,  Joker, Gollum, Abagnale, Jack Sparrow, terminator, Michael Cera, Petyr Baelish, Arya Stark, Socyopath Tyrell, Tywin Lannister, Grandma Tyrell, Khal, Frank Underwood, Lex Luther/Tony Stark, Jessie Pinkman, Hermiony, Juno, Barney, Saul Goodman, Kaylee, River, Shepherd, Inara, Jayne Cobb, Zoe, Mycroft, Mrs. Hudson, Claire Underwood, James Sawyer, Kate Austen, Hurley, Benjamin Linus!!, Lost Physicist, Debra Morgan, James Doakes, Trinity killer, Angel Batista, Creepy Chinese guy(Dexter), James Willson, 
Harvey, Rachel, Donna, Louis, Jessica, Howard,
Linsday, Bad girl from(FaG), Cool Nerd(FaG), Marshal, Theodore Bagwell, Alexander Mahone, Gretchen, Agent Kellerman, 
Grandpa(Up), Louie CK, 
Abed, Britta, Annie, Shirley, Troy, Pierce,
Satanist(Silicon Valley), Displeasing,


* Plots
- Fight a villain/opponent
- Get out of trouble
    Escape plan that went wrong
    Get setup for a crime
    Stray on a dangeroud planet
- Retrieve an artifact. Find/Steal a thing //inception
- Resque someone
- Break into/out of something
- Solve a crime
- Exact revenge
- Fix what is wrong with the world
- Protect a place from an army //whorehouse, alien invasion
- Get/impress a girl/person
- Win/close a deal
- Escape from agents/creatures
- Take over something //villain, world
- Any other goal of value
    Make money. 
    Make a Discovery.
    Unite the worlds.
    Take home to the adventure place(Up)
    Return a girl home(Monsters Inc)
    Restore a family(back to the future) //get out of trouble
    Bring humans back to earh(WALL-E)
    Retain a memory of a girl(Eternal sunshine)
    Win at political stuff

** IInc?
- Somebody attacks you on the street
- Aliens/other dimension creatures are coming
- Dark overlord rises
- Competition/sport
- You got setup for a crime
- Stray in a dangerous place
- Priceless artifact has been stolen
- Your friend is in danger, have to resque
- Crime appened and needs to be solved
- Somebody hurt you
- Enemies attack your castle
- You've met a girl who is ignoring you
- Once in a lifetime opportunity that you need to win whatever it takes
- Somebody is chacing you
- You're out of money and out of stuff
- Your best friends had a huge fight and now hate each other
- Somebody gave you something very dangerous to take care of(like a pet)
- 
More specific:  
- 
- 
- 
- 

* Source stories
HPMOR; RaM; futurama; Inception; matrix; Firefly; incredibles; avengers; x-men; train your dragon;star wars;MIB;fallout
pinky and brain; airbender; got; lost; pirates of the carribean;batman;LOTR; fight club; terminator; alien;liar liar; mask; jurrasic parck; resident evil;
silicon valley; californication; fringe; lost; community; HIMYM; walking dead; futurama; sherlock; Dexter; house of cards; house; dr who; suits; prison break; breaking bad; d&d; halflife; portal; megamind; dispeakable me; lion king; walle; ice age; shrek;  emperors new groove; inspector gadget; 

* Genres
- Complex plots //house of cards - one politics plot
- Supervillain story //megamind/dispeakable me
- HIMYM - lovestory/romcom. 
  Yes, that too. Be creative.
- Mystery/Whodunit //sherlock. Remember yam killing.

* De-bono
Topic/area/niche > breakdown, concrete
  
** Focus/Creative pause:
- ask a question nobody has asked before
- pick a random thing and decide to challenge/improve it.  
   
- Boring mediocre cliches/default assumptions.
- Things to improve, problems to solve.
- challenge everything and ask why?
   
** Challenge:
- General "new ideas in the area x"
- Improve "How to improve x?"
- Solve. What's wrong with it?
  Solve problem "Is there a problem? How can I solve it?"
- DBC - Why are we doing it this way? Better way?
- Drop/escape it - what would we do without it?
  Alternatives?
– Achieve  

** Jump:
Goal - create:
crazy/very-not-true/wrong/over-the-top/wide-gap
(comic reality? Looking for crazy.)

- Reversal
- Exaggeration
- Random
- Reorder
- Connect to field
- Perspective (Max angle)
- Straightforward
  

** Move: //~crazy association?? by seriously thinking on crazy stuff??
Goal - create/find crazy/new
connection/association/reinterpretation/alternative
by seriously thinking on crazy stuff.
(Rationally explain the insane thing, and this is how you find a conector??)

- Positive aspect
- Difference
- Imagine
- Situation in which it could be useful
  
** Types of connectors
- Explanation
- Outcome
- Behavior
- Reaction
- Interpretation
- Assumption
- My opinion
- Meaning(word/phrase)
//metaphor  
  
** Tools  
- Breakdown
  Find a concrete
- Branch away on different levels
- List of 5 things
- Find the core, get rid of fluff.

- Connector(on multiple levels) > Alternatives!! //> exaggerate the gap
- Jump(crazy) > Move(seriously thinking on crazy stuff, finding an association)  

Once you've got new idea - unfold/essay.

** Comedy
//General vibe(maybe sometimes has something to do with):

- crazy/very-not-true/wrong/over-the-top/wide-gap
- connection/association/reinterpretation/alternative
- seriously think on crazy stuff.
- break/defeat/shatter the pattern/assumption/expectation
- wrong prediction/expectation/assumption
quick deletion of a false version/old-pattern
detect mistaken reasoning
   

* Essays
*** Creativity
***** DeBono Creativity Inventions
****** Creative pause.
****** Jump
****** Move
****** Breakdown
****** Penetrate(MVP, EP) + CI > Pivot-Steer
****** Drop expectations, list of 5.
****** Strip away everything unnecessary. Get to the core. Minimal thing.
****** Paradox of choice, good enough principle.
****** Reverse enineering.
****** No rules just tools.
****** Comedy
       Joke structure.
       AIMA epiphany dean's book. Defeat expectations.
****** Imagination.
****** Jump-unfold.
       Get into the world and explore.
****** Get most of the ideas in the process of writing.      
****** Niching down to make ideas
****** Curiosity. How it works.
****** Ideas of value. Not about typing/expression.
       Substance, story. Fuck grammar. 

****** How I want to write - concise, simple, etc.

****** Reasons we enjoy movies. Comedy. Mastery. Etc.
       Avatar. Association.
       Value. Closer/farther from goal.
       Conflict. That makes sense.
       Event - moving closer to or away from the goal.  
* Other
** Names
Michael
Seth
Alex
Frank
Jack
Ted

* 2015-01-16
So!
Setting.
Character(s).
Plot.
Premise.

Befriend a monster in a nuclear wasteland....
 



