* Process 4x128
> Prompt. (SciFi-HC. Story-HC.)
> Plot. (Escalate > Lose)
> Climax. (Solution. Setups. Default Lanes.)
> Crazy Lanes > Move/Express


> Prompt. (SciFi-HC. Story-HC.)
  - What are some interesting places to explore?
  - Which character do I want to place there?
  - What can go wrong?
> Plot. (Escalate > Lose)
  - How can it escalate?
  - What could be the point of no-return?
  - How can he lose?
> Climax. (Solution. Setups. Default Lanes.)
  - How could he turn the lose into win?
> Crazy Lanes > Move/Express
  - What are the expected lanes, patterns climax makes you to recognize?
  - What are some crazy alternative lanes?
  - How can I associate/explain them?

* Climaxes
- Lily tied in the angar, criminals asking for sensitive flash > flying away on stolen plane
- Linus and Turtle vs robots. Escalate-lose - surrounded by robots? turn into a win - infect the skynet
- Jane manipulates her dummie scared boss into fighting and winning the necromancer
- 
- 
- 
- 
- 

* Setups
- Guy working out in the gym
- Students sitting on a boring lecture
- Guy sitting in front of the computer in his office
- One person pointing a gun at another person
- Dude waking up and drinking coffee
- Girl sitting on a couch doodling someting in a notebook
- 2 people on a raft in a middle of the ocean/dude on a tropical island
- Lawyer siting in his office/dude playing a guitar
  
* Ideas
**** Open Source
Like Max could hack /?microsoft's? website and a whole bunch of stuff, opensource /?windows? code, and company thinks it's better to roll with it than the emberrasment of admitting that they were so hacked. If they even can prove that they aren't just going back on their word.
Or Max could even SE them to make them do it from the inside =)

**** Airbender, element magic.(worst person to have it?)
Displeasing guy(gets superpowers. And Kaylee, his assistant.

Meanwhile, Jane was sitting outside of the office, tweaking the latest security software that run their corporation, when she learned that her boss developed magical powers.
One of her laptops keeped the skype session with her boss opened, since she was trying to convince him not to open that kitten picture link in his email.
Apparently he forgot about that in the last 15 minutes, and now was abscentmidedly picking his nose while reading something on his computer.
She didn't tell him that she could see him immediately, and after awhilie it was just awkward,
 2Suddnly that picture grabbed her attention, as she saw something like a purple explosion from behind her bosses head. Boss clearly didn't notice any of that, as he was paying all his  attention to the computer screen. Jane just wanted to tell him something, as she noticed that a pen he held in his hand, again, unbeknown to him, disappeared in the burst of flames.
Boss kept reading something on his screen, laughin from time to time.

//some dummie gets magical powers, and a cool clever guy has to manipulate this idiot into doing what he wants. Cool. But dummie needs to also be cool and likeable. Maybe not stupid but just not the kind of character to use magical powers very well.
     
**** Harvey/Jessica vs zombies.
Harvey was sitting in his office when he didn't notice that something strange was happening in the city. He didn't notice because his office was on the 60th floor of a huge scyscraper.
This was a regular morning,

**** Benjamin Linus and Turtle fight robot rebellion.
Ben and Sal stood back to back, shooting lasers at crowrs of robots that were trying to get through the doors of their building. Robots were humanoids, and looked a lot like scary sceletons. Sal wondered - why would you make a robot looking that weird? Granted, friendly-looking robots were looking even creepier, but then again - what is the point of designing a thing to look outright malicious? Almost like designers hoped that these robots will rebel. You could hardly see these things assembling cars or cleaning the streets or babysitting.
     
**** Stanford/MIT. Juno. Aliens are coming.
Zoe was on her 3rd course studying computational biology when these weird students started appearing more and more often on campus. It was hard to pinpoint what they all had in common, besides the strange behavior and aura of weirdness around them. They've seemed to come from all over US, in no particular pattern, they weren't similar in cloth, appearance, or a behavior, yet
all had something strangely in common and alien....
	
**** Canada. Twins. Dark overlod rises. ?
Jim was spending his summer at his father's in Canada.
When he

**** Small town. Draco. Stray in a dangerous place.
Matt didn't expect this trip to turn out so weird.
He was on a trip to photograph places around this small town, when things started to go wrong.
Before I continue I'd like to mention that Matt was kind of a dick. Or maybe a better word would be an "antihero", but that's not how his girlfriend called him when they broke up. Or his boss, right before firing him.

**** Mancave. Jeff(hot guy). Your friend is in danger. ?
Jeff was playing xbox on his couch when his telephone rang.
"If you want your friend to be well - meet me at the corner of x and y"

**** Hollywood. Abed. Someone is chasing you.
Ted was running through the sunny streets of Los Angeles, being chased by 3 angry old people.

**** Detroit. Michael Cera. You're out of money and stuff/stray.
Mike never expected to be stranded in such place with no money but here he was.
Trusting that weird taxi guy was a mistake. Hell, getting into this terrifying city was a mistake.
Why did I do that, again?
 
**** Small Tropical island. Troy and Pierce. Priceless artifact has been stolen. ?
Investigation of a mysterious diappearance of an old x lead Rick and Dave to this tropical island.

**** Pyramides. Hermioiny/Kaylee. Somebody attacks you on the streeet.
Lily was visiting pyramids for the first time.
When she was trying to buy a thing on the street
- 3 americans in expensive suits asked her to come with them.
She ran.

**** Agents vs aliens. Michael Cera and Theodore Bagwell fights aliens.
  Mike looked at the giant antient starship hanging above the canyon.
It was hanging there for generations, as long as anyone could remember.
Nobody have ever understood how did it work, nobody was even able to enter that thing.
Because they were living in the cavemen times.
And cavemen could never get into the spaceship.

**** Grandma Tyrell vs Saul Goodman
  It was a regular day for a Saul Goodman.
He helped one guy to get out of jail for dealing weed, and helped that creepy lady to get every penny her husband has ever owned or will ever own.

**** House vs Jessie Pinkman fighting Dinosurs
Loudest roar echoed through the entire forest, as a humongous foot landed in 2 meters from the Jessie. After a second of stunned silence, Greg grabbed him by hist shirt and started running in the opposite from the foot direction. They will take time to explain what is going on later, now it was clearly the time to run. They had no reasons to suspect that T-Rex would have any interest in them - after all, he would hopefully perfer a much bigger prey, but this pack of raptors on the other hand....     
**** Frank Underwood + HIMYM(haha, nice one. He's telling his children)
Frank was having his first date in a long long time. After 20 years of ruthlessly climbing the corporate ladder in the biggest and meanest software corporation of all time he almost forgot what's it like to talk to a person without a clear agenda or buttons to push.     

**** Space pirates crew stray on a mysterious planet, try to escape.
   //lost(plane crash/mysterious island)+Firefly

**** Fallout meets How to Train your Dragon
   Befriend a monster in a nuclear wasteland
**** Nerdy Magician + Pirates
   Nerdy magician kidnapped by pirares, escape-befriend them
   //silicon valley+pirates+prison break
**** Character realizes he is in a story
   Writer, extremely genre aware, recognizes he got into a story.  
   Uses it as a power, predicts stuff, argues with a narrator.
   //californication(cocky dickhead writer)+LOTR

   Like "wait, that can't happen! Even if magic is real, this part is
   just a cliche, it dkesnt make sense! I'm in a story!!"
   "narrator: and trolls blasted into the building
   - hey, why'd you do that to me, dickhead? x and y is why you
   never do that in a story.
   narrator: oh, nevermind then, okay, trolls don't blast into the 
   building.
   haha, maybe narrator gets even angry and dumps bucket onto 
   a character's head or something"
**** MIB for paranormal.
   MIB+ fringe(paranormal scientists) Comedy. World where werewolves/magic/
   etc are real, and agents have to deal with it.
   Yeah, like a newbie agent is assigned a mission to deal with a 
   stray werewolves!! Not HP world, or maybe heck, maybe HP!!    
   Imagine US agents who are aware of magic.


**** Connected dreams
**** Abandoned spaceship? > Abandoned company with loot.
**** Train job? > Steal something physical in transit.
**** Laser? > Pure break, enter, download data job.
**** Niska? > get in trouble with criminals.
**** Ariel? > 2 of them are downloading data as alarm goes off(no betrayal).
**** Whorehouse? > protect a website from ddos or someting? Fight off another group of hackers.
**** HPMOR battles? > Wining Defcon hacking competition!! (to get in the door somewhere, or fun)
**** Wizengamot? > Defending net neutrality, making sure a bullshit law doesn't get approved.
**** Saving Hermiony? > They freak out that Alice could be in danger, when they come to save her turns out that she kicked all the butts there were to be to kick.
**** Inception? > Convince a guy to not sell his company or something, by helping/protecting/manipulating him. Maybe all 3.
**** Prison Break? > Government agents are onto them.
**** Pranks competition? > Competition between Max and Kyle, bet, who beats whom and such. Maybe breaking into 2 teams, 3 vs 3. on sometihng.
**** Harry vs Tracey? > They all have decided to try LSD, when something comes up they need full alertness with.
**** Harry vs peeves? > trolls come together on reddit to ddoss/attack them/their friends company or some website that they like? And they destroy trolls from the inside or some such.
**** Agents? > They decide to infiltrate some company to find out the secrets, something super secret and exciting. Not as a job but because they need to know.
**** Criminals take someone hostage?
**** Woman, husband, the bank where he holds his money?
**** Competition with city college. Get back the throne.
**** Abed (/de)inception in dreamatorium
**** Somebody blew up the studyroom and they all have lost their memories

**** cloverfield? 
**** paintball sequel?
**** computer game sequel?  
**** Harry vs Twins - pranks comppetition //+More of the cans of comed-tea  
**** Harry vs Tracey - rationalist on a love potion
**** Harry vs peevez.
**** Agents
     
**** Harry vs Dumbledor, over taking control of his money!
**** Ron is in love with Hermiony. He knows harry is superior, gives his best to come up with a plan to defeat his evil.
**** Harry wants to do experiments on ghosts, they are too proud
**** Belka strikes back. Takes Nevill hostage?
**** Retreive books from the restricted section
**** social engineering lecture
**** Supervillain apprentice  
**** Max, steal data, villains. in Futurama this time.

* CIs
1. "Reality is normal, you're weird."
   There is a perfectly reasonable explanation for everything; things only seem strange because of your own ignorance.
2. Enemies. being innately evil. 
   that seems obvious enough.+correspondence bias(kickiNg wending ,machine)
3. Majority is always wrong. most popular cant be the best.
4. Availability heuristic!!
   Now that is an actually interesting challenge Id like to explain on a metaphor.
5. Don't trust people just because they sound wise or confident, see if their arguments make sense. no ad homeniem either.
6. don't choose to believe in things just because it feels better
   what can be destroyed by the truth shall be. reality is already is, admitting it doesnt make it worse.
7. never attribute to malice what can be explained by incompetence. sse randomness. not center around yourself.
 dont see purpose where  there isnt.
8. PG: see the world through your own eyes, imitate what you like, not what you're "supposed to" like.
9. You can't just use skepticism or doubt ti defeat any argument you dislike.   
10. people choose the more charismatic politician and thenn rationalize  backwards
    same with words. say things that make them feel good, they will rationalize agreeingvwith you afterwards.
11. Broken Window theory
   Somebody made a small mistake,
   neglected a tiny flaw,
   and it gradually escalated into a disaster?
12. Straw-Man conversation
13. Trust  science/rationaliqty more than  your eyes??
14. practice vs talent
15. adjusting emotions/beliefs according to probabikities? If it is 10 times less likely it should be 10 times less scary?
    
Fake explanations? What you predict matters, not what you explain? Names of things don't tell you anything.
Reversed stupidity is not intelligence?
like they dont believe something because bad tribe says that?
science vs politics?
Kyle uses/teaches someone a reciprocation trick?
Everyone is totally winging it all the time. Confident people are just better at hiding it.
If you really believed something, you'd act like it were were true.
It doesnt matter how it looks, just what it causes. Utilitwrian stuff.
//Morals are made up?
Dont expect life to be fair, do what works. What is true and what works is what matters, not fairness.
rationalization
dont grow blank, dont allow yourself to ignore things.
  

- Understand>Automate, don't rely on subconscousness?
- Self teaching vs education?
- Deliberate practice?
- Zooming into a niche?
- Tracer bullets
- Programming by conincidence
- Broken windows/Stone soup and boiled frogs.
- Do what's important, not what' urgent?
- Straw man argument
- Creative pause
- Limitations breed creativity
- Massive action to learn
- Biases(some)
* Settings
** Locations
- Pyramides
- Stanford/MIT
- Hot startup
- Boston Dynamics/google R&D
- Canada
- Australia
- Small town
- New York
- Law firm
- Collegehumor workplace
- Mancave, xbox, couch
- Hollywood
- Small african village
- Detroit
- Metro
- Submarine
- Jet
- Abandoned hydron collider or such
- Small tropical island
- 
** Professions:
- Scientist/Mathematitian/Engineer/Programmre
- PUA
- Detective
- CEO
- Writer/Artist
- Drug dealer
- Douchebag Lawyer
- Evil Machiavellian polititian(not only in politics, in any field)
- 
  
//Check all of them in the past/present/future

** Technology
- Portal gun
- Some stimulants? //dog, rick and morty...
- Null-waves
- Flamethrower
- Invisibility ray //in incredibles
- Force fields
- Robots
- The actual thing that exists, MRI brain images like in house
  (with awesome limitations too, even if more advanced! 
  Like you can only read what the person is thinking, or the blurred images, 
  or you need a giant machine)
- Using ML to predict the future
- simple AI
- Mutants
- Time Machine - probably unnecessary, breaks too many htings.
- MIB mind eraser.
- Simulated reality(RaM). + mind reading = storing memories.
- RaM - parallel worlds
- Perfect imagination superpower
** Fiction worlds  
- Vikings vs dragons. //How to train your dragon
- Agents vs Aliens //MIB
- Nuclear Postapoc //fallout
- Laboratory, mice //pinky and brain/ratotuille
- Pirates plus Magic //Pirates of the Carribean
- Robot world //Terminator/WALL-E
- Alien planet //Alien
- Dinosaurs //Jurrasic Parck, land before time
- Zombies //Resident Evil/Walking Dead
- Illegal underground Science research lab. //fringe
- Element magic + knights/fantasy //Airbender + GOT

** Magic //Superpowers
- Portals /teleportation
- Superspeed
- Levitation
- Fireballs
- Invisibility,
- Force Fields
- Turning into animals
- Reading minds
- Seer
- Ghosts/portraits
- Magical creatures
- Time-travel
- Obliviate
- Mind vessel  
Killing/Sleeping..
Superstrength, flexibility or whatnot...

* Characters
** Archetypes  
Universal core chars:
> Main
Hermiony //Kaylee?
Juno     //Robin/Lindsay,
Harry,   //Frank/House/WW/etc
Twins    //Barney
Draco.   //

> Secondary
Jeff
Marshal/Seth/Turtle,
Abed,
Captain,

> Other
Louie Ck
Michael Cera
Shirley
Pierce/Chang/Dean
Troy
Luna
Grandma Tyrell
* Names
http://fantasynamegenerators.com/native_american_names.php#.VOrk6sv0CBZ
Misu
Bimisi
Iye
Ahnu
Nayate
Yiska
Kuruk
Roul
Armen
Draven
Aaron
Maldar
Bryne
Akir
Liam 
Keon
Glen
Keara
Gory
Xiri
Darna
Belric
Baseros
Bolog
Joggor
Fecha
Avas
Malo
Iana
Agdi

Ugu
Uba
Zoug
Ayla
Gobur

http://www.erblist.com/erbmania/paluldon/paluldonglossary.html
http://public.wsu.edu/~delahoyd/cavespeak.html
akara - fire



  
** Male Names
- a Alan, Alex
- b 
- c
- d David
- e Eric
- f Frank, Fred
- g
- h
- i
- j Jack
- k Kyle
- l
- m Matt, Max, Michael
- n
- o
- p
- q
- r
- s Sal, Saul, Seth
- t Ted
- u
- v Vincent
- w
- x
- y
- z

** Female Names
- a Alice, Amber, Annie, Aria
- b Britta
- c Cyntia
- d Donna, Deanarys
- e Emily
- f Fiona
- g Ginnie
- h 
- i Inara
- j Jane, Juno, Jessica
- k Kate
- l Lily, Lindsay, Lila, Lumen
- m Megan
- n Nicole
- o 
- p Penny
- q 
- r Rita, Ramona, Rachel, Rose
- s Skyler
- t Trinity
- u
- v Viki, Violet
- w 
- x Xena
- y
- z Zoe   

* Plots
Goals:  
- Fight a villain/opponent
- Get out of trouble
    Escape plan that went wrong
    Get setup for a crime
    Stray on a dangeroud planet
- Retrieve an artifact. Find/Steal a thing //inception
- Resque someone
- Break into/out of something
- Solve a crime
- Exact revenge
- Fix what is wrong with the world
- Protect a place from an army //whorehouse, alien invasion
- Get/impress a girl/person
- Win/close a deal
- Escape from agents/creatures
- Take over something //villain, world
- Any other goal of value
    Make money. 
    Make a Discovery.
    Unite the worlds.
    Take home to the adventure place(Up)
    Return a girl home(Monsters Inc)
    Restore a family(back to the future) //get out of trouble
    Bring humans back to earh(WALL-E)
    Retain a memory of a girl(Eternal sunshine)
    Win at political stuff

IInc's:
- Somebody attacks you on the street
- Aliens/other dimension creatures are coming
- Dark overlord rises
- Competition/sport
- You got setup for a crime
- Stray in a dangerous place
- Priceless artifact has been stolen
- Your friend is in danger, have to resque
- Crime appened and needs to be solved
- Somebody hurt you
- Enemies attack your castle
- You've met a girl who is ignoring you
- Once in a lifetime opportunity that you need to win whatever it takes
- Somebody is chacing you
- You're out of money and out of stuff
- Your best friends had a huge fight and now hate each other
- Somebody gave you something very dangerous to take care of(like a pet)
- 
More specific:  
- 
- 
- 
- 

* Examples
Stories:  
HPMOR; RaM; futurama; Inception; matrix; Firefly; incredibles; avengers; x-men; train your dragon;star wars;MIB;fallout
pinky and brain; airbender; got; lost; pirates of the carribean;batman;LOTR; fight club; terminator; alien;liar liar; mask; jurrasic parck; resident evil;
silicon valley; californication; fringe; lost; community; HIMYM; walking dead; futurama; sherlock; Dexter; house of cards; house; dr who; suits; prison break; breaking bad; d&d; halflife; portal; megamind; dispeakable me; lion king; walle; ice age; shrek;  emperors new groove; inspector gadget; 

Characters:
Tyler Durden, Cannibal Lecter,  Joker, Gollum, Abagnale, Jack Sparrow, terminator, Michael Cera, Petyr Baelish, Arya Stark, Socyopath Tyrell, Tywin Lannister, Grandma Tyrell, Khal, Frank Underwood, Lex Luther/Tony Stark, Jessie Pinkman, Hermiony, Juno, Barney, Saul Goodman, Kaylee, River, Shepherd, Inara, Jayne Cobb, Zoe, Mycroft, Mrs. Hudson, Claire Underwood, James Sawyer, Kate Austen, Hurley, Benjamin Linus!!, Lost Physicist, Debra Morgan, James Doakes, Trinity killer, Angel Batista, Creepy Chinese guy(Dexter), James Willson, 
Harvey, Rachel, Donna, Louis, Jessica, Howard,
Linsday, Bad girl from(FaG), Cool Nerd(FaG), Marshal, Theodore Bagwell, Alexander Mahone, Gretchen, Agent Kellerman, 
Grandpa(Up), Louie CK, 
Abed, Britta, Annie, Shirley, Troy, Pierce,
Satanist(Silicon Valley), Displeasing,

Genres:
- Complex plots //house of cards - one politics plot
- Supervillain story //megamind/dispeakable me
- HIMYM - lovestory/romcom. 
  Yes, that too. Be creative.
- Mystery/Whodunit //sherlock. Remember yam killing.

* De-bono
Topic/area/niche > breakdown, concrete
  
** Focus/Creative pause:
- ask a question nobody has asked before
- pick a random thing and decide to challenge/improve it.  
   
- Boring mediocre cliches/default assumptions.
- Things to improve, problems to solve.
- challenge everything and ask why?
   
** Challenge:
- General "new ideas in the area x"
- Improve "How to improve x?"
- Solve. What's wrong with it?
  Solve problem "Is there a problem? How can I solve it?"
- DBC - Why are we doing it this way? Better way?
- Drop/escape it - what would we do without it?
  Alternatives?
– Achieve  

** Jump:
Goal - create:
crazy/very-not-true/wrong/over-the-top/wide-gap
(comic reality? Looking for crazy.)

- Reversal
- Exaggeration
- Random
- Reorder
- Connect to field
- Perspective (Max angle)
- Straightforward
  

** Move: //~crazy association?? by seriously thinking on crazy stuff??
Goal - create/find crazy/new
connection/association/reinterpretation/alternative
by seriously thinking on crazy stuff.
(Rationally explain the insane thing, and this is how you find a conector??)

- Positive aspect
- Difference
- Imagine
- Situation in which it could be useful

// why? how? explain? imagine?
** Types of connectors
- Explanation
- Outcome
- Behavior
- Reaction
- Interpretation
- Assumption
- My opinion
- Meaning(word/phrase)
//metaphor  
  
** Tools  
- Breakdown
  Find a concrete
- Branch away on different levels
- List of 5 things
- Find the core, get rid of fluff.

- Connector(on multiple levels) > Alternatives!! //> exaggerate the gap
- Jump(crazy) > Move(seriously thinking on crazy stuff, finding an association)  

Once you've got new idea - unfold/essay.

** Comedy
//General vibe(maybe sometimes has something to do with):

- crazy/very-not-true/wrong/over-the-top/wide-gap
- connection/association/reinterpretation/alternative
- seriously think on crazy stuff.
- break/defeat/shatter the pattern/assumption/expectation
- wrong prediction/expectation/assumption
quick deletion of a false version/old-pattern
detect mistaken reasoning


Whoah, it can be humongously valuable and convenient!!
Maybe that's too much, there's so many types of everything in every situation.
Well, I can at least miss certain kinds of stuff I want to often check/not miss.
>>>> Elements/Assumtions:
- Setting. Environment.
  - Objects. Surrounding. Stuff you're using. Parts of the objects(wheels in a car),
  - Purpose of an object
  - Cloth
  - Environment - room, road, etc?
  - Other characters you interact with.
- Character's actions(?). Character Behavior/Reaction to something.
- Character's opinion on something. Character's attitude/motivation.
- Explanation/Interpretation of this situation
- Expected outcome
- ++++ find more. that kind of stuff.
- Meaning(word/phrase)
//metaphor

* Essays
*** Creativity
***** DeBono Creativity Inventions
****** Creative pause.
****** Jump
****** Move
****** Breakdown
****** Penetrate(MVP, EP) + CI > Pivot-Steer
****** Drop expectations, list of 5.
****** Strip away everything unnecessary. Get to the core. Minimal thing.
****** Paradox of choice, good enough principle.
****** Reverse enineering.
****** No rules just tools.
****** Comedy
       Joke structure.
       AIMA epiphany dean's book. Defeat expectations.
****** Imagination.
****** Jump-unfold.
       Get into the world and explore.
****** Get most of the ideas in the process of writing.      
****** Niching down to make ideas
****** Curiosity. How it works.
****** Ideas of value. Not about typing/expression.
       Substance, story. Fuck grammar. 

****** How I want to write - concise, simple, etc.

****** Reasons we enjoy movies. Comedy. Mastery. Etc.
       Avatar. Association.
       Value. Closer/farther from goal.
       Conflict. That makes sense.
       Event - moving closer to or away from the goal.  
* //
** My Perfect Worlds
*** Commpunity 
*** Incredibles
  - my HPMOR // Worm,
*** Singularity
    = RaM meets Futurama //Firefly
*** Mirage
    = Deep meets Inception //permutation

** Ideas
   
*** Incredibles:  
- battle
- getting into the school
- social engineering lecture
- Supervillain apprentice  
  //Suits + megamind/dispeakable me


*** Singularity:
- Max, steal data, villains. in Futurama this time.
- Abandoned spaceship? > Abandoned company with loot.
- Train job? > Steal something physical in transit.
- Laser? > Pure break, enter, download data job.
- Niska? > get in trouble with criminals.
- Ariel? > 2 of them are downloading data as alarm goes off(no betrayal).
- Whorehouse? > protect a website from ddos or someting? Fight off another group of hackers.
- HPMOR battles? > Wining Defcon hacking competition!! (to get in the door somewhere, or fun)
- Wizengamot? > Defending net neutrality, making sure a bullshit law doesn't get approved.
- Saving Hermiony? > They freak out that Alice could be in danger, when they come to save her turns out that she kicked all the butts there were to be to kick.
- Inception? > Convince a guy to not sell his company or something, by helping/protecting/manipulating him. Maybe all 3.
- Prison Break? > Government agents are onto them.
- Pranks competition? > Competition between Max and Kyle, bet, who beats whom and such. Maybe breaking into 2 teams, 3 vs 3. on sometihng.
- Harry vs Tracey? > They all have decided to try LSD, when something comes up they need full alertness with.
- Harry vs peeves? > trolls come together on reddit to ddoss/attack them/their friends company or some website that they like? And they destroy trolls from the inside or some such.
- Agents? > They decide to infiltrate some company to find out the secrets, something super secret and exciting. Not as a job but because they need to know.
- Criminals take someone hostage?
- Woman, husband, the bank where he holds his money?
  
 
*** Community:  
- Competition with city college. Get back the throne.
- Abed (/de)inception in dreamatorium

- Somebody blew up the studyroom and they all have lost their memories
- cloverfield? 
- paintball sequel?
- computer game sequel?  
  
  
*** HPMOR:
- Harry vs Twins - pranks comppetition //+More of the cans of comed-tea  
- Harry vs Tracey - rationalist on a love potion
- Harry vs peevez.
- Agents  
  
- Harry vs Dumbledor, over taking control of his money!
- Ron is in love with Hermiony. He knows harry is superior, gives his best to come up with a plan to defeat his evil.
- Harry wants to do experiments on ghosts, they are too proud
- Belka strikes back. Takes Nevill hostage?
- Retreive books from the restricted section
- Broomstick battle and battle where all three generals get assasinated at the beginning
	I want to hear about Draco thinking that between Goyle and himself, it's an easy win for Dragon Army. And then he decides to have Goyle attack Sunshine single-wandedly. I want to hear about how Hermione can barely get off the ground and after 30 seconds of Goyle, Sunshine's chances are all up to Ron Weasley and Susan Bones. Who then decide their only hope is to run toward the Chaos Legion and hope the Chaotics and Dragons will focus on each other until the numbers are more even.

	I want to hear Harry's aerial battle tactics, how Tracy Davis and Theodore Nott gang up on Draco, and how well Finnigan and Thomas fare against the other Dragons. And ultimately, I want it to come down to Harry vs. Goyle pitting training and experience vs. talent, creativity, and intelligence. All while Harry is too distracted to notice that his broom always flies in the direction it's pointed.
- Battle where everyone is for themselves.
- More of the cans of comed-tea  


*** Diverse short stories(/premises):
***** Agents vs aliens. Michael Cera and Theodore Bagwell fights aliens.
  Mike looked at the giant antient starship hanging above the canyon.
It was hanging there for generations, as long as anyone could remember.
Nobody have ever understood how did it work, nobody was even able to enter that thing.
Because they were living in the cavemen times.
And cavemen could never get into the spaceship.

***** Grandma Tyrell vs Saul Goodman
  It was a regular day for a Saul Goodman.
He helped one guy to get out of jail for dealing weed, and helped that creepy lady to get every penny her husband has ever owned or will ever own.

***** Airbender, element magic.(worst person to have it?)
Displeasing guy(gets superpowers. And Kaylee, his assistant.

Meanwhile, Jane was sitting outside of the office, tweaking the latest security software that run their corporation, when she learned that her boss developed magical powers.
One of her laptops keeped the skype session with her boss opened, since she was trying to convince him not to open that kitten picture link in his email.
Apparently he forgot about that in the last 15 minutes, and now was abscentmidedly picking his nose while reading something on his computer.
She didn't tell him that she could see him immediately, and after awhilie it was just awkward,
 2Suddnly that picture grabbed her attention, as she saw something like a purple explosion from behind her bosses head. Boss clearly didn't notice any of that, as he was paying all his  attention to the computer screen. Jane just wanted to tell him something, as she noticed that a pen he held in his hand, again, unbeknown to him, disappeared in the burst of flames.
Boss kept reading something on his screen, laughin from time to time.

//some dummie gets magical powers, and a cool clever guy has to manipulate this idiot into doing what he wants. Cool. But dummie needs to also be cool and likeable. Maybe not stupid but just not the kind of character to use magical powers very well.
     
***** Harvey/Jessica vs zombies.
Harvey was sitting in his office when he didn't notice that something strange was happening in the city. He didn't notice because his office was on the 60th floor of a huge scyscraper.
This was a regular morning,

***** Benjamin Linus and Turtle fight robot rebellion.
Ben and Sal stood back to back, shooting lasers at crowrs of robots that were trying to get through the doors of their building. Robots were humanoids, and looked a lot like scary sceletons. Sal wondered - why would you make a robot looking that weird? Granted, friendly-looking robots were looking even creepier, but then again - what is the point of designing a thing to look outright malicious? Almost like designers hoped that these robots will rebel. You could hardly see these things assembling cars or cleaning the streets or babysitting.
     
***** House vs Jessie Pinkman fighting Dinosurs
Loudest roar echoed through the entire forest, as a humongous foot landed in 2 meters from the Jessie. After a second of stunned silence, Greg grabbed him by hist shirt and started running in the opposite from the foot direction. They will take time to explain what is going on later, now it was clearly the time to run. They had no reasons to suspect that T-Rex would have any interest in them - after all, he would hopefully perfer a much bigger prey, but this pack of raptors on the other hand....     
***** Frank Underwood + HIMYM(haha, nice one. He's telling his children)
Frank was having his first date in a long long time. After 20 years of ruthlessly climbing the corporate ladder in the biggest and meanest software corporation of all time he almost forgot what's it like to talk to a person without a clear agenda or buttons to push.     

***** Pyramides. Hermioiny/Kaylee. Somebody attacks you on the streeet.
Lily was visiting pyramids for the first time.
When he was trying to buy a thing on the street
- 3 americans in expensive suits asked her to come with them.
She ran.

***** Stanford/MIT. Juno. Aliens are coming.
Zoe was on her 3rd course studying computational biology when these weird students started appearing more and more often on campus. It was hard to pinpoint what they all had in common, besides the strange behavior and aura of weirdness around them. They've seemed to come from all over US, in no particular pattern, they weren't similar in cloth, appearance, or a behavior, yet
all had something strangely in common and alien....
	
***** Canada. Twins. Dark overlod rises.
Jim was spending his summer at his father's in Canada.
When he

***** Small town. Draco. Stray in a dangerous place.
Matt didn't expect this trip to turn out so weird.
He was on a trip to photograph places around this small town, when things started to go wrong.
Before I continue I'd like to mention that Matt was kind of a dick. Or maybe a better word would be an "antihero", but that's not how his girlfriend called him when they broke up. Or his boss, right before firing him.

***** Mancave. Jeff(hot guy). Your friend is in danger.
Jeff was playing xbox on his couch when his telephone rang.
"If you want your friend to be well - meet me at the corner of x and y"

***** Hollywood. Abed. Someone is chasing you.
Ted was running through the sunny streets of Los Angeles, being chased by 3 angry old people.

***** Detroit. Michael Cera. You're out of money and stuff/stray.
Mike never expected to be stranded in such place with no money but here he was.
Trusting that weird taxi guy was a mistake. Hell, getting into this terrifying city was a mistake.
Why did I do that, again?
 
***** Small Tropical island. Troy and Pierce. Priceless artifact has been stolen.
Investigation of a mysterious diappearance of an old x lead Rick and Dave to this tropical island.


***** Space pirates crew stray on a mysterious planet, try to escape.
    //lost(plane crash/mysterious island)+Firefly


***** Fallout meets How to Train your Dragon
    Befriend a monster in a nuclear wasteland
***** Nerdy Magician + Pirates
    Nerdy magician kidnapped by pirares, escape-befriend them
    //silicon valley+pirates+prison break
***** Character realizes he is in a story
    Writer, extremely genre aware, recognizes he got into a story.  
    Uses it as a power, predicts stuff, argues with a narrator.
    //californication(cocky dickhead writer)+LOTR

    Like "wait, that can't happen! Even if magic is real, this part is
    just a cliche, it dkesnt make sense! I'm in a story!!"
    "narrator: and trolls blasted into the building
    - hey, why'd you do that to me, dickhead? x and y is why you
    never do that in a story.
    narrator: oh, nevermind then, okay, trolls don't blast into the 
    building.
    haha, maybe narrator gets even angry and dumps bucket onto 
    a character's head or something"
***** MIB for paranormal.
    MIB+ fringe(paranormal scientists) Comedy. World where werewolves/magic/
    etc are real, and agents have to deal with it.
    Yeah, like a newbie agent is assigned a mission to deal with a 
    stray werewolves!! Not HP world, or maybe heck, maybe HP!!    
    Imagine US agents who are aware of magic.
***** Connected dreams


*** Prompts
- social engineering lecture
- Supervillain apprentice  
      
***** //
     
8 posts:
- Nerdy magician
- Incredibles - first day
- Pacman competition
- Singularity bottom-up  
- Essay(comes last)
//
- ?Singularity - max and criminals
- //Xkcd collegehumor ~ singularity?
- ?Mirage -?
- HPMOR 
     
- breaking bad - scientist turns bad
- portal - experiment subject
   



** Characters
Max, Amber, Sal, and Violet.
- Max(Harry) evil witty brilliant jerk.
- Sal(Twins/Barney) Twins meet Seth/Jeff/Hot-guy kind of laidback. Guy from cracked!!
- Amber(Hermiony/Kaylee) infinitely energetic and cheerful Hermiony. Smart kind of clever. //a bit dorky.
- Violet/Alice(Juno) leader/captain. Mal meets Annie. Strategic thinker, goal oriented. 
   
//Kyle
  
Conflicts:
Amber. Max - jerk, Kyle - irresponsible?
Kyle. Max - evil(?), Amber - boring/too "straight"?.
Max.

And if Violet is a leader she may have a reason for being in there.
Imagine Juno but also Annie-like leader, Captain... They would fight with Max all the freakin time. Also good. Not Hermiony-good, but "what's wrong with you, jerk?" kind of good. Captain-good.


Comedy jokes stick figures.
- Max evil-barney hacker
- Alice - Annie/Kaylee
- Kyle - hot guy, troy, boss
- Vincent - nerdy nerd
//sal
building a startup but sucking at it.
in some kind of crazy courses or a startup school...

No Kyle, Sal instead.
Hot guy, troy, boss, good at social stuff - yeah, Kyle and Sal converge. And that's funnier.
Oh, and maybe a girl could be nerdy for a change.
Hmmm..
Max - evil barney hacker guy.
Sal - goofy swaim hustler guy.
Alice - nerdy annie kaylee energetic naive girl.
that's enough.

Yep, table, couch, chair.
Max evil guy,
Sal goofy hot guy,
Alice - cheerful nerdy girl.
Dialogue, go!
Abed would be sad and unnecessary there, Max is already the clever guy.
Robin could fit, though not necessary either.
Maybe they could be against robin, vincent, and richard or some such.
   
Universal core chars:
> Main
Hermiony //Kaylee?
Juno     //Robin/Lindsay,
Harry,   //Frank/House/WW/etc
Twins    //Barney
Draco.   //

> Secondary
Jeff
Marshal/Seth/Turtle,
Abed,
Captain,

> Other
Louie Ck
Michael Cera
Shirley
Pierce/Chang/Dean
Troy
Luna
Grandma Tyrell

Not-Singularity:
- Max(Harry) 	- hacker. satanist/house/harry/frank/ww/etc /security
- Alice(Juno) 	- SE. /Juno/Robin/Lindsay/Violet.. /designer
- Amber(Hermiony/Kylee)         - Pyro  engineer. / hardware
- Vincent(Abed) - Scientist. ML. Cool nerd from freaks and geeks, Abed /backend, systems, ml  
- Kyle(Twins/Barney)

//leader, captain /programmer  
//Seth - dude hairy guy from silicon valley, seth, dude from big hero /rent, can talk anybody

David(Draco?)

Or:
Like Max, Amber, Sal, and Violet.

- Max(Harry) evil witty brilliant jerk.
- Sal(Twins/Barney) Twins meet Seth/Jeff/Hot-guy kind of laidback. Guy from cracked!!
Laidback Hot-confident Twins..... That cracked guy!! HEY. That is an interesting image.
He is laid back, and a cool dude, and hot-confident, and I can totally see him be a prankster without being a jerk!! Cracked guy but also clever, Twins-kind-of-clever. Totally fits.
Maybe a bit Marshal. Not sure what that means.
- Amber(Hermiony/Kaylee) infinitely energetic and cheerful Hermiony. Smart kind of clever. //a bit dorky.
Yeah, just good and smart and dorky would be a bit lame, but smart and infinitely energetic could be really cool.
//Alice(Juno) 	- SE. /Juno/Robin/Lindsay/Violet.. /designer
Like the captain!!
He-ey. I wonder if alice could possibly be leader/captain. That would be weird enough...
Strategic thinker, goal oriented... also seems like a strange mix but could be interesting....
Not like a leader, not like you can really lead thouse people, but the...
Well, Annie actually does that thing. Where she says - that's it, we are doing this, we are going there, and quit fucking around.
16 yo Juno like captain. Badass.

- Vincent(Abed/Sheldon?) - Scientist. ML. Cool nerd from freaks and geeks, Abed /backend, systems, ml  

Conflicts:
Amber. Max - jerk, Kyle - irresponsible?
Kyle. Max - evil(?), Amber - boring/too "straight"?.
Max.


Incredibles:
- Violet(Juno)
- Dash(Twins)
- Kyle(Harry)
- Pyro(Kylee)
- Magneto(Troy?)
- Seer(Luna+bright/positive/cheerful)

Singularity:
- Max - hacker. satanist/house/harry /security
- Amber - engineer. kaylee. / hardware
- Alice - SE. lindsay/violet/.. /designer
- Kyle - leader, captain /programmer
- Seth - dude hairy guy from silicon valley, seth, dude from big hero /rent, can talk anybody
- Mike? Alex? - Scientist. ML. Cool nerd from freaks and geeks, Abed /backend, systems, ml  
  
*** Examples  
Tyler Durden, Cannibal Lecter,  Joker, Gollum, Abagnale, Jack Sparrow, terminator, Michael Cera, Petyr Baelish, Arya Stark, Socyopath Tyrell, Tywin Lannister, Grandma Tyrell, Khal, Frank Underwood, Lex Luther/Tony Stark, Jessie Pinkman, Hermiony, Juno, Barney, Saul Goodman, Kaylee, River, Shepherd, Inara, Jayne Cobb, Zoe, Mycroft, Mrs. Hudson, Claire Underwood, James Sawyer, Kate Austen, Hurley, Benjamin Linus!!, Lost Physicist, Debra Morgan, James Doakes, Trinity killer, Angel Batista, Creepy Chinese guy(Dexter), James Willson, 
Harvey, Rachel, Donna, Louis, Jessica, Howard,
Linsday, Bad girl from(FaG), Cool Nerd(FaG), Marshal, Theodore Bagwell, Alexander Mahone, Gretchen, Agent Kellerman, 
Grandpa(Up), Louie CK, 
Abed, Britta, Annie, Shirley, Troy, Pierce,
Satanist(Silicon Valley), Displeasing,

** Prompts
- Abandoned spaceship? > Abandoned company with loot.
- Train job? > Steal something physical in transit.
- Laser? > Pure break, enter, download data job.
- Niska? > get in trouble with criminals.
- Ariel? > 2 of them are downloading data as alarm goes off(no betrayal).
- Whorehouse? > protect a website from ddos or someting? Fight off another group of hackers.
- HPMOR battles? > Wining Defcon hacking competition!! (to get in the door somewhere, or fun)
- Wizengamot? > Defending net neutrality, making sure a bullshit law doesn't get approved.
- Saving Hermiony? > They freak out that Alice could be in danger, when they come to save her turns out that she kicked all the butts there were to be to kick.
- Inception? > Convince a guy to not sell his company or something, by helping/protecting/manipulating him. Maybe all 3.
- Prison Break? > Government agents are onto them.
- Pranks competition? > Competition between Max and Kyle, bet, who beats whom and such. Maybe breaking into 2 teams, 3 vs 3. on sometihng.
- Harry vs Tracey? > They all have decided to try LSD, when something comes up they need full alertness with.
- Harry vs peeves? > trolls come together on reddit to ddoss/attack them/their friends company or some website that they like? And they destroy trolls from the inside or some such.
- Agents? > They decide to infiltrate some company to find out the secrets, something super secret and exciting. Not as a job but because they need to know.
- Criminals take someone hostage?
- Woman, husband, the bank where he holds his money?
- Competition with city college. Get back the throne.
- Abed (/de)inception in dreamatorium
- Somebody blew up the studyroom and they all have lost their memories
- cloverfield? 
- paintball sequel?
- computer game sequel?  
- Harry vs Twins - pranks comppetition //+More of the cans of comed-tea  
- Harry vs Tracey - rationalist on a love potion
- Harry vs peevez.
- Agents  
- Harry vs Dumbledor, over taking control of his money!
- Ron is in love with Hermiony. He knows harry is superior, gives his best to come up with a plan to defeat his evil.
- Harry wants to do experiments on ghosts, they are too proud
- Belka strikes back. Takes Nevill hostage?
- Retreive books from the restricted section
- social engineering lecture
- Supervillain apprentice  
- Max, steal data, villains. in Futurama this time.
